<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>app</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <sonar.projectKey>go-coverage</sonar.projectKey>
        <sonar.projectName>go-coverage</sonar.projectName>
        <sonar.language>go</sonar.language>
        <sonar.sources>./internal/utils/relative_path.go</sonar.sources>
        <sonar.tests>./internal/utils/relative_path_test.go</sonar.tests>
        <sonar.go.coverage.reportPaths>./coverage.out</sonar.go.coverage.reportPaths>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>4.0.0.4121</version>
            </plugin>
        </plugins>
    </build>
</project>
